const POST_INFO_SUCCESS = "POST_INFO_SUCCESS";
const POST_INFO_FAIL = "POST_INFO_FAIL";
const POST_INFO_REQUEST = "POST_INFO_REQUEST";

const SEARCH_SUCCESS = "HOME_SUCCESS";
const SEARCH_FAIL = "HOME_FAIL";
const SEARCH_REQUEST = "HOME_REQUEST";
