export const POST_INFO_SUCCESS = "POST_INFO_SUCCESS";
export const POST_INFO_FAIL = "POST_INFO_FAIL";
export const POST_INFO_REQUEST = "POST_INFO_REQUEST";

export const SEARCH_SUCCESS = "HOME_SUCCESS";
export const SEARCH_FAIL = "HOME_FAIL";
export const SEARCH_REQUEST = "HOME_REQUEST";
